### ISSUE TITLE
[BE] EC2 서버에 Https 적용

### ISSUE THREAD

**Issue by 2-eun-ji** [codestates-seb/seb45_main_031#156]
## Https 적용
- [x] DNS 구매 및 EC2 연결 설정
- [x] SSL 인증서 발급
- [x] Nginx 설정 - https 적용
- [x] 포스트맨 테스트
- [x] 웹브라우저 테스트

**Comment by KIHYUN940** [comment]
Https 별거 없네요!! 고생 많으셨습니다ㅎㅎㅎ

**Comment by 2-eun-ji** [comment]
Nginx, 로드 밸런서 이용하여 도메인 연결 후 Https 적용 완료했습니다. 이슈 닫습니다 🤸🌈
