### ISSUE TITLE
[FE] 회원가입

### ISSUE THREAD

**Issue by jooy45** [codestates-seb/seb45_main_031#4]
![회원가입](https://github.com/codestates-seb/seb45_main_031/assets/129937290/8ff7fbc0-3baa-4f22-9705-9b132a992a2b)
###  뷰
- [x] -구글 버튼
- [x] -닉네임
- [x] -패스워드
- [x] -패스워드 확인 입력창
- [x] -유효성 검사 문구
- [x] -확인 버튼
- [x] -취소 버튼

 ### 기능
- [x] #190
- [x] -유효성 검사를 한다.
- [x] -이메일(아이디) , 닉네임 중복 검사를 한다.
- [x] -패스워드와 패스워드 확인 비교란이 있다.
- [x] -확인 버튼 클릭 시 회원가입 후 로그인 페이지로 이동한다.

### 필수데이터

- [x] 닉네임
- [x] 이메일
- [x] 패스워드 ( 최소 8글자 이상, 1자 이상의 영문, 1개 이상의 숫자 )

**Comment by kimmand0o0** [comment]
구글 오어스 #190 이슈로 adv로 변경 후 이슈 닫겠습니다.
