### ISSUE TITLE
[FE] 2주차 멘토링 피드백 리팩토링

### ISSUE THREAD

**Issue by kimmand0o0** [codestates-seb/seb45_main_031#74]
[코드 리뷰 정리]
##
1. import 문의 순서와 정리
라이브러리와 작성한 코드를 구분(그룹핑)하는 것이 가장 쉬운 방법이다.
그룹 사이에는 한줄 띄기를 사용해서 구분해주면 좋다.
2. const와 let에 대해 조금 더 고민해보기
3. 변수 선언과 컴포넌트 등 그룹핑을 하는 부분들은 띄어쓰기로 가독성 높혀주기.
4. 컴포넌트 명을 정할 때 최대한 구체적인 단어로 묘사하는 것이 좋다. > 가독성 증가
5. 한 변수명을 사용 할 때 단어와 단어 구분을 위하여 단어 첫 스펠링은 대문자로 작성.
6. 공통 변수명 한번에 바꾸기 > 윈도우 : f2
7. styled component 사용 시 변수명에 styled라는 말이 들어가면 안됨.
변수명은 구체적이지만 간결 해야한다.
8. 소스 코드만 보고도 웹 페이지의 전체 레이아웃이 상상이 되도록 만들어 주는 걸 고민해보기.

**Comment by kimmand0o0** [comment]
김혜란 피드백 받은 부분 리팩토링 완료입니다.

**Comment by kimmand0o0** [comment]
@lynne-choi @jooy45
2주차 피드백 리팩토링 완료 되었을까요??
완료되었으면 처리하고 3차 멘토링 이슈 열려고 합니다!

**Comment by jooy45** [comment]
권주영 피드백 받은 부분 리팩토링 완료입니다.

**Comment by lynne-choi** [comment]
네 2주차 피드백 리팩토링 완료입니다!

**Comment by kimmand0o0** [comment]
감사합니다! 이슈 닫겠습니다!
